laguage: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travics CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r changsu-project-webservice *
  - mkdir -p deploy
  - mv changsu-project-webservice.zip deploy/changsu-project-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings
    bucket: changsu-project-webservice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipients:
      - happycs0203@naver.com
